apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounting-system
  template:
    metadata:
      labels:
        app: accounting-system
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: my-container
          image: 169296002015.dkr.ecr.ap-south-1.amazonaws.com/accounting_system:d3c45e1 # Replace with your actual image name
          envFrom:
            - secretRef:
                name: accounting-system-aws-secret
            - secretRef:
                name: postgres-db-pwd
            - configMapRef:
                name: postgres-db-config
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
