apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounting-system
  template:
    metadata:
      labels:
        app: accounting-system
    spec:
      containers:
        - name: my-container
          image: accounting-system # Replace with your actual image name
          envFrom:
            - secretRef:
                name: postgres-db-pwd
            - configMapRef:
                name: postgres-db-config
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
