apiVersion: v1
kind: Secret
metadata:
  name: accounting-system-aws-secret
  namespace: default
stringData:
  AWS_REGION: "ap-south-1"
  AWS_SECRET_ACCESS_KEY: "" # Replace with your AWS secret access key
  AWS_ACCESS_KEY_ID: "" # Replace with your AWS access key ID
  AWS_ACCOUNT: "" # Replace with your AWS account ID
