apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-config
data:
  # property-like keys; each key maps to a simple value
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "dummy"
  POSTGRES_DB: "postgres"
  POSTGRES_MAX_CONNECTIONS: "5"
  POSTGRES_HOST: "postgres-db-postgresql.default.svc.cluster.local"
  POSTGRES_connect_timeout_seconds: "10"
  POSTGRES_PASSWORD: "dummy_pwd"
  POSTGRES_WAIT_TIMEOUT_SECONDS: "5"
  POSTGRES_POOL_RECYCLING_METHOD: "Clean"
  POSTGRES_APPLICATION_NAME: "accounting-system"
  POSTGRES_APP_DB: "accounting_system"
