services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file: test_environment.env
    depends_on:
       db:
          condition: service_healthy
  db:
    image: "postgres:16.0"
    ports:
      - "5432:5432"
    env_file: test_environment.env
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} --dbname ${POSTGRES_DB} -t 1'" ]
      start_interval: 1s
      start_period: 20s
      interval: 1s
      timeout: 500ms
      retries: 4
