[package]
name = "db_prep_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.19.5"
env_logger = "0.10.0"
log = "0.4.17"
clap = { version = "4.3.3", features = ["derive"] }