apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting-temporal-java-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounting-temporal-java-worker
  template:
    metadata:
      labels:
        app: accounting-temporal-java-worker
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: my-container
          image: 169296002015.dkr.ecr.ap-south-1.amazonaws.com/accounting_temporal_java_worker:37cdedd # Replace with your actual image name
          env:
            - name: IS_KUBERNETES_ENV
              value: "true"
            - name: TEMPORAL_FRONTEND_SERVICE_NAME
              value: accounting-temporal-frontend
            - name: TEMPORAL_FRONTEND_SERVICE_NAME
              value: accounting-temporal-frontend
            - name: TEMPORAL_FRONTEND_SERVICE_NAME
              value: accounting-temporal-frontend
            - name: TEMPORAL_FRONTEND_SERVICE_NAME
              value: accounting-temporal-frontend
            - name: TEMPORAL_FRONTEND_SERVICE_NAME
              value: accounting-temporal-frontend
            - name: TEMPORAL_FRONTEND_SERVICE_NAME
              value: accounting-temporal-frontend
            - name: TEMPORAL_FRONTEND_SERVICE_NAME
              value: accounting-temporal-frontend
            - name: TEMPORAL_FRONTEND_SERVICE_NAME
              value: accounting-temporal-frontend
            - name: TEMPORAL_FRONTEND_SERVICE_NAME
              value: accounting-temporal-frontend
          #          envFrom:
          #            - secretRef:
          #                name: postgres-db-pwd
          #            - configMapRef:
          #                name: postgres-db-config
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
