apiVersion: v1
kind: Service
metadata:
  name: accounting-temporal-java-worker
spec:
  selector:
    app: accounting-temporal-java-worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  