[package]
name = "invoicing_calculations"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
thiserror = "1.0.40"
[dev-dependencies]
rstest = "0.18.1"
spectral = "0.6.0"