apiVersion: apps/v1
kind: Deployment
metadata:
  name: doc-generation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: doc-generation
  template:
    metadata:
      labels:
        app: doc-generation
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
        - name: my-container
          image: doc-generation # Replace with your actual image name
#          envFrom:
#            - secretRef:
#                name: postgres-db-pwd
#            - configMapRef:
#                name: postgres-db-config
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
