name: accounting_temporal_worker

on:
  push:
    paths:
      - 'accounting_temporal_worker/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'accounting_temporal_worker/**'
    branches: [ "main" ]
env:
  AWS_REGION: ap-south-1
permissions:
  id-token: write
  contents: read

jobs:
  build:
    if: ${{contains(github.event.head_commit.message,'#bld_img') && (github.event.ref=='refs/heads/main')}}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./accounting_temporal_worker
    steps:
      - uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: arn:aws:iam::169296002015:role/ecr_automation_github
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: | # optional
            ./*.gradle*
            ./**/gradle-wrapper.properties
      - run: ./gradlew buildImage --no-daemon
        working-directory: ./accounting_temporal_worker

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: accounting_temporal_java_worker
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker load -i ./build/jib-image.tar
          docker tag accounting-temporal-java_worker:$IMAGE_TAG $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        working-directory: ./accounting_temporal_worker
