name: Rust

on:
  push:
    paths:
      - '.github/workflows/rust.yml'
      - 'accounting_system_rust/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'accounting_system_rust/**'
    branches: [ "main" ]

env:
  AWS_REGION: ap-south-1
  CARGO_TERM_COLOR: always

jobs:
  build:
    defaults:
      run:
        working-directory: ./accounting_system_rust

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
#    - run: echo ${{contains(github.event.head_commit.message,'#bld_img') && (github.event.ref=='refs/heads/main')}}
#    - run: echo ${{env.MESSAGE}}
#    - uses: Swatinem/rust-cache@v2
#      with:
#        workspaces: |
#          ./accounting_system_rust
#

#    - name: build and run tests
#      run: cargo test

  docker_image:
    needs:
      - build
    if: ${{contains(github.event.head_commit.message,'#bld_img') && (github.event.ref=='refs/heads/main')}}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: arn:aws:iam::169296002015:role/ecr_automation_github
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Set short sha
        id: sha_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v5
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: accounting_system
          IMAGE_TAG: ${{ steps.sha_short.outputs.sha_short }}
        with:
          context: ./accounting_system_rust/
          push: true
          tags: ${{env.REGISTRY}}/${{env.REPOSITORY}}:${{env.IMAGE_TAG}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false