name: Rust

on:
  push:
    paths:
      - '.github/workflows/rust.yml'
      - 'accounting_system_rust/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'accounting_system_rust/**'
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  MESSAGE: ${{contains(github.event.push.head_commit.message,'#bld_img')}}
jobs:
  build:
    defaults:
      run:
        working-directory: ./accounting_system_rust

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: echo ${{toJSON(github.event)}}
    - run: echo ${{env.MESSAGE}}
#    - uses: Swatinem/rust-cache@v2
#      with:
#        workspaces: |
#          ./accounting_system_rust
#
#    - name: build and run tests
#      run: cargo test
