name: Rust

on:
  push:
    paths:
      - 'accounting_system_rust/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'accounting_system_rust/**'
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  MESSAGE: ${{contains(github.event.push.head_commit.message,'#bld_img')}}
jobs:
  build:
    defaults:
      run:
        working-directory: ./accounting_system_rust

    runs-on: ubuntu-latest

    steps:
    - run: echo ${{github.event.push.head_commit.message}}
    - run: echo ${{env.MESSAGE}}
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          ./accounting_system_rust

    - name: build and run tests
      run: cargo test
